### PR TITLE
OEL-000: Improve offacanvas button.

### PR DESCRIPTION
**Pull request by drishu**
Improve the button look

### CODE REVIEW

**Review by GilNovacomm — DISMISSED** [review]
Tested works perfectly.

**Review by drishu — COMMENTED** [review]
Screenshot 2021-09-21 at 13 16 10
The new filter options button

**Comment by escuriola** [comment]
We want always an icon and that icon with the button?

**Review by escuriola — DISMISSED** [review]

**Review by escuriola — APPROVED** [review]

**Review by GilNovacomm — APPROVED** [review]
Approved.

**Pull request merged**
